version: '2'
services:
  ohdsui:
    image: ohdsui
    ports:
     - "3000:3000"
    volumes:
     - .:/code
    depends_on:
     - ohdsrest
  ohdsrest:
    image: ohdsrest
    hostname: ohds
    domainname: ohds.rest
    ports:
     - "8080:8080"
    expose: 
      - "8080"
